name:                ppmpa-hs
version:             2.7.0.0
synopsis:            "Progressive Photon Mapping by Haskell"
category:            "Computer Graphics"
github:              "githubuser/ppmpa-hs"
license:             BSD3
author:              eijian
maintainer:          akagi.eiji@gmail.com
copyright:           "Copyright (c) 2021, eijian"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Ray Tracer using Progressive Photon Mapping method

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- containers
- deepseq >= 1.3
- deepseq-generics >= 0.1.1.1
- kdt
- mersenne-random
- numeric-prelude >= 0.4.2
- parsec
- parsec-numbers
- random
- split
- text
- vector


library:
  source-dirs: src

executables:
  pm:
    main:                Main-pm.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - ppmpa-hs
  rt:
    main:                Main-rt.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - ppmpa-hs
    - time

tests:
  ppmpa-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ppmpa-hs
